### PR TITLE
Updated the build file, allowing .git folders to be pulled down for tagg...

### PR DESCRIPTION
**Pull request by NGlasl**
...ed modules. There's also a default script included to check the git status of each child directory.

### CODE REVIEW

**Comment by tractorcow** [comment]
Perhaps a bit of documentation on the new scripts in build/readme.txt would be good? :D

**Comment by NGlasl** [comment]
I was planning on adding some documentation for them in the wiki, unless you think that should go into the readme?

**Comment by nyeholt** [comment]
Can't hurt to have it in the README - people using things outside the context of github won't necessarily check here. 

Also, the name of the 'status' script might be better as 'inner-status' or 'recursive-status' ? A bit more descriptive as to what it does.

**Comment by NGlasl** [comment]
These changes have now been applied.

**Pull request merged**
